version: "3.9"

services:
  fraud-api:
    build:
      context: .
      dockerfile: myapp.dockerfile
    container_name: fraud-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    restart: unless-stopped
    environment: {} 
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
